languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "Eike.in"
contentDir = 'content/de'


[params]
displayName = "DE"
isoCode = "de"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_transparent.png"
description = "Ich mache Sachen"

[author]
name = "Eike"
image = "logo.jpg"
links = [ { email = "mailto:me@eike.in" }, { github = "https://github.com/LarvenStein" }, { instagram = "https://www.instagram.com/printer.planet/" }, { mastodon = "https://mastodon.online/@LarvenStein" } ]
bio = "Ich mache Sachen"
headline = "Ich mache Sachen"
