languageCode = "en"
languageName = "English"
weight = 1
title = "Eike.in"
contentDir = 'content/en'


[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_transparent.png"
description = "I do stuff"

[author]
name = "Eike"
image = "logo.jpg"
links = [ { email = "mailto:me@eike.in" }, { github = "https://github.com/LarvenStein" }, { instagram = "https://www.instagram.com/printer.planet/" }, { mastodon = "https://social.eike.in/@aikhae" } ]
bio = "I do stuff"
headline = "I do stuff"
