languageCode = "en"
languageName = "English"
weight = 1
title = "Eike.in"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_transparent.png"
description = "I do stuff"

[[params.author.links]]
email = "mailto:me@eike.in"

[[params.author.links]]
 github = "https://github.com/LarvenStein"

[[params.author.links]]
instagram = "https://www.instagram.com/printer.planet/"

[[params.author.links]]
bluesky = "https://bsky.app/profile/eike.in"

[[params.author.links]]
mastodon = "https://social.eike.in/@aikhae"


["params.author"]
name = "Eike"
image = "logo.jpg"
bio = "I do stuff"
headline = "I do stuff"
